const UserList = [
  {
    "id": 1,
    "name": "Rafael Pedrocco",
    "username": "rpedrocco0",
    "age": 32,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 6,
        "name": "Vin Baxstair",
        "username": "vbaxstair5",
        "age": 20,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 2,
    "name": "Glenn Pillman",
    "username": "gpillman1",
    "age": 35,
    "nationality": "PHILIPPINES",
    "friends": [],
  },
  {
    "id": 3,
    "name": "Romy Brocklesby",
    "username": "rbrocklesby2",
    "age": 23,
    "nationality": "PHILIPPINES",
    "friends": [
      {
        "id": 5,
        "name": "Liam Joffe",
        "username": "ljoffe4",
        "age": 31,
        "nationality": "PHILIPPINES",
      },
    ],
  },
  {
    "id": 4,
    "name": "Twila Caress",
    "username": "tcaress3",
    "age": 21,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 5,
        "name": "Liam Joffe",
        "username": "ljoffe4",
        "age": 31,
        "nationality": "PHILIPPINES",
      },
    ],
  },
  {
    "id": 5,
    "name": "Liam Joffe",
    "username": "ljoffe4",
    "age": 31,
    "nationality": "PHILIPPINES",
    "friends": [
      {
        "id": 4,
        "name": "Twila Caress",
        "username": "tcaress3",
        "age": 21,
        "nationality": "INDONESIA",
      },
      {
        "id": 3,
        "name": "Romy Brocklesby",
        "username": "rbrocklesby2",
        "age": 23,
        "nationality": "PHILIPPINES",
      },
    ],
  },
  {
    "id": 6,
    "name": "Vin Baxstair",
    "username": "vbaxstair5",
    "age": 20,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 1,
        "name": "Rafael Pedrocco",
        "username": "rpedrocco0",
        "age": 32,
        "nationality": "INDONESIA",
      },
      {
        "id": 8,
        "name": "Birk Beining",
        "username": "bbeining7",
        "age": 29,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 7,
    "name": "Perl Antrum",
    "username": "pantrum6",
    "age": 35,
    "nationality": "PHILIPPINES",
    "friends": [],
  },
  {
    "id": 8,
    "name": "Birk Beining",
    "username": "bbeining7",
    "age": 29,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 6,
        "name": "Vin Baxstair",
        "username": "vbaxstair5",
        "age": 20,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 9,
    "name": "Regan Kitteridge",
    "username": "rkitteridge8",
    "age": 35,
    "nationality": "PHILIPPINES",
    "friends": [],
  },
  {
    "id": 10,
    "name": "Justino Grunwall",
    "username": "jgrunwall9",
    "age": 28,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 8,
        "name": "Birk Beining",
        "username": "bbeining7",
        "age": 29,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 11,
    "name": "Goldi Garrit",
    "username": "ggarrita",
    "age": 21,
    "nationality": "PHILIPPINES",
    "friends": [
      {
        "id": 12,
        "name": "Halette Thorpe",
        "username": "hthorpeb",
        "age": 26,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 12,
    "name": "Halette Thorpe",
    "username": "hthorpeb",
    "age": 26,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 11,
        "name": "Goldi Garrit",
        "username": "ggarrita",
        "age": 21,
        "nationality": "PHILIPPINES",
      },
    ],
  },
  {
    "id": 13,
    "name": "Charo Foucard",
    "username": "cfoucardc",
    "age": 24,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 11,
        "name": "Goldi Garrit",
        "username": "ggarrita",
        "age": 21,
        "nationality": "PHILIPPINES",
      },
      {
        "id": 12,
        "name": "Halette Thorpe",
        "username": "hthorpeb",
        "age": 26,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 14,
    "name": "Daffy Dilleston",
    "username": "ddillestond",
    "age": 25,
    "nationality": "JAPAN",
    "friends": [
      {
        "id": 16,
        "name": "Alexei Gadman",
        "username": "agadmanf",
        "age": 31,
        "nationality": "INDONESIA",
      },
      {
        "id": 12,
        "name": "Halette Thorpe",
        "username": "hthorpeb",
        "age": 26,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 15,
    "name": "Adelind Mashal",
    "username": "amashale",
    "age": 20,
    "nationality": "MALAYSIA",
    "friends": [
      {
        "id": 19,
        "name": "Emory Vamplus",
        "username": "evamplusi",
        "age": 25,
        "nationality": "INDONESIA",
      },
      {
        "id": 19,
        "name": "Emory Vamplus",
        "username": "evamplusi",
        "age": 25,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 16,
    "name": "Alexei Gadman",
    "username": "agadmanf",
    "age": 31,
    "nationality": "MALAYSIA",
    "friends": [
      {
        "id": 17,
        "name": "Kirsten Coughtrey",
        "username": "kcoughtreyg",
        "age": 35,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 17,
    "name": "Kirsten Coughtrey",
    "username": "kcoughtreyg",
    "age": 35,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 16,
        "name": "Alexei Gadman",
        "username": "agadmanf",
        "age": 31,
        "nationality": "MALAYSIA",
      },
    ],
  },
  {
    "id": 18,
    "name": "Stern MacFaell",
    "username": "smacfaellh",
    "age": 35,
    "nationality": "MALAYSIA",
    "friends": [],
  },
  {
    "id": 19,
    "name": "Emory Vamplus",
    "username": "evamplusi",
    "age": 25,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 12,
        "name": "Halette Thorpe",
        "username": "hthorpeb",
        "age": 26,
        "nationality": "INDONESIA",
      },
    ],
  },
  {
    "id": 20,
    "name": "Ellsworth Coyish",
    "username": "ecoyishj",
    "age": 28,
    "nationality": "INDONESIA",
    "friends": [
      {
        "id": 12,
        "name": "Halette Thorpe",
        "username": "hthorpeb",
        "age": 26,
        "nationality": "INDONESIA",
      },
    ],
  },
];

const MovieList = [
  {
    "id": 1,
    "title": "Cold Prey III (Fritt Vilt III)",
    "genre": ["Horror", "Mystery", "Thriller"],
    "release_date": "12/28/2003",
    "rating": 9.1,
  },
  {
    "id": 2,
    "title": "Kids Are All Right, The",
    "genre": ["Comedy", "Drama", "Romance"],
    "release_date": "4/17/2000",
    "rating": 9.5,
  },
  {
    "id": 3,
    "title": "Super",
    "genre": ["Action", "Comedy", "Drama"],
    "release_date": "9/5/2005",
    "rating": 9.3,
  },
  {
    "id": 4,
    "title": "Fun",
    "genre": ["Comedy", "Drama", "Romance"],
    "release_date": "5/31/2012",
    "rating": 6.5,
  },
  {
    "id": 5,
    "title": "Death Hunt",
    "genre": ["Action", "Drama", "Thriller"],
    "release_date": "9/22/2021",
    "rating": 7.2,
  },
  {
    "id": 6,
    "title": "Seven Ways from Sundown",
    "genre": ["Action", "western"],
    "release_date": "11/12/2018",
    "rating": 7.4,
  },
  {
    "id": 7,
    "title": "When Night Is Falling",
    "genre": ["Drama", "Romance"],
    "release_date": "1/9/2013",
    "rating": 9.5,
  },
  {
    "id": 8,
    "title": "Vampire Journals",
    "genre": ["Fantasy", "Horror", "Mystery"],
    "release_date": "5/20/2009",
    "rating": 7.1,
  },
  {
    "id": 9,
    "title": "How to Deal",
    "genre": ["Comedy", "Drama", "Romance"],
    "release_date": "12/2/2018",
    "rating": 9.8,
  },
  {
    "id": 10,
    "title": "Mega Shark vs. Crocosaurus",
    "genre": ["Action", "Drama", "Thriller"],
    "release_date": "6/12/2002",
    "rating": 9.5,
  },
];

export { UserList, MovieList };
